### NumPy vs Python

NumPy arrays: NumPy arrays are homogeneous, meaning all elements in the array are of the same data type<br/>
Python lists: Python lists can contain elements of different data types, making them heterogeneous<br/>
Performance<br/>
Memory Usage<br/>
Ease to use<br/>

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5])

In [5]:
print(x)

[1 2 3 4 5]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.shape

(5,)

In [8]:
y=x.reshape(1,5)
print(y)

[[1 2 3 4 5]]


In [9]:
y.shape

(1, 5)

In [10]:
data=np.array([[1,2,3],[3,4,5]])
print(data)

[[1 2 3]
 [3 4 5]]


In [11]:
data.shape

(2, 3)

In [12]:
type(data)

numpy.ndarray

In [40]:
data.itemsize

4

In [13]:
np.arange(0,10,3)



array([0, 3, 6, 9])

In [14]:
print(np.shape)

<function shape at 0x000001F29CB132E0>


In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
full_array = np.full((2, 2), 4.5)
print(full_array)

[[4.5 4.5]
 [4.5 4.5]]


In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
arr.shape

(3, 3)

In [19]:
print(arr.ndim)

print(arr.size)

print(arr.dtype)

2
9
int32


In [64]:
arr

array([[ 1,  2,  3,  4],
       [ 5, 25, 25, 25],
       [ 9, 25, 25, 25]])

In [ ]:
a = np.array([1, 2, 3])
appended = np.append(a, [7, 8])

Useful for vectorized operations like

In [21]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [22]:
print("Addition:", arr1+arr2)

Addition: [11 22 33 44 55]


In [23]:
print("Substraction:", arr1-arr2)

Substraction: [ -9 -18 -27 -36 -45]


In [24]:
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)
print("Modulor: ", arr1%arr2 )

Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Modulor:  [1 2 3 4 5]


In [25]:
print(np.sqrt(arr1+arr2))

print(np.exp(arr1+arr2))

print(np.log(arr1*arr2))

[3.31662479 4.69041576 5.74456265 6.63324958 7.41619849]
[5.98741417e+04 3.58491285e+09 2.14643580e+14 1.28516001e+19
 7.69478527e+23]
[2.30258509 3.68887945 4.49980967 5.07517382 5.52146092]


In [26]:
print(np.sqrt(arr1-arr2))

[nan nan nan nan nan]


C:\Users\Dell\AppData\Local\Temp\ipykernel_15680\2498429054.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr1-arr2))


Array Slicing

In [27]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [28]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [30]:
arr[1][2]

7

Modify elements in array

In [31]:
arr[1][2]=100

print(arr)

[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [32]:
arr[1:,1:]=25

In [33]:
arr

array([[ 1,  2,  3,  4],
       [ 5, 25, 25, 25],
       [ 9, 25, 25, 25]])

Statistical operations

In [34]:
data = np.array([1, 2, 3, 4, 5])

In [35]:
np.mean(data)

3.0

In [36]:
print(np.std(data))

np.var(data)

1.4142135623730951


2.0

In [37]:
np.median(data)

3.0

In [38]:
np.mode(data)

AttributeError: module 'numpy' has no attribute 'mode'

Logical Operations

In [ ]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data>=5) & (data<=8)])
print(data[(data>=5) | (data<=8)])
print(data[(data>=5) ^ (data<=8)])

[5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  9 10]


In [42]:
print(data[(data>=5) ~ (data<=8)])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (183965113.py, line 1)

In [47]:
y = np.array([[1, 2, 3],
                    [4, 5, 6]])

In [48]:
x=y.T  #Transpose
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [51]:
random_integers = np.random.randint(1, 10, size=5)
print(random_integers)
random_pick=np.random.choice(['a','b','c'])
print(random_pick)

[7 6 1 4 8]
b


~ for 2D

In [53]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

result = np.matmul(matrix_a, matrix_b)

result

array([[19, 22],
       [43, 50]])

In [58]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transposed_matrix = np.transpose(matrix)

transposed_matrix

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
np.max(matrix)


6

In [60]:
np.min(matrix)

1

In [61]:
a = np.array([[1, 2], [3, 4]])


b = a.ravel()
print(b)

c = a.flatten()
print(c)

[1 2 3 4]
[1 2 3 4]
