In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
x=np.array([1,2,3,4,5])

In [6]:
print(x)

[1 2 3 4 5]


In [7]:
type(x)

numpy.ndarray

In [9]:
x.shape

(5,)

In [14]:
y=x.reshape(1,5)
print(y)

[[1 2 3 4 5]]


In [15]:
y.shape

(1, 5)

In [17]:
data=np.array([[1,2,3],[3,4,5]])
print(data)

[[1 2 3]
 [3 4 5]]


In [20]:
data.shape

(2, 3)

In [22]:
type(data)

numpy.ndarray

In [36]:
np.arange(0,10,3)



array([0, 3, 6, 9])

In [44]:
print(np.shape)

<function shape at 0x00000266D3F0C180>


In [45]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
arr.shape

(3, 3)

In [54]:
print(arr.ndim)

print(arr.size)

print(arr.dtype)

2
9
int32


In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Useful for vectorized operations like

In [62]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

In [63]:
print("Addition:", arr1+arr2)

Addition: [11 22 33 44 55]


In [64]:
print("Substraction:", arr1-arr2)

Substraction: [ -9 -18 -27 -36 -45]


In [65]:
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)
print("Modulor: ", arr1%arr2 )

Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Modulor:  [1 2 3 4 5]


In [72]:
print(np.sqrt(arr1+arr2))

print(np.exp(arr1+arr2))

print(np.log(arr1*arr2))

[3.31662479 4.69041576 5.74456265 6.63324958 7.41619849]
[5.98741417e+04 3.58491285e+09 2.14643580e+14 1.28516001e+19
 7.69478527e+23]
[2.30258509 3.68887945 4.49980967 5.07517382 5.52146092]


In [76]:
print(np.sqrt(arr1-arr2))

[nan nan nan nan nan]


C:\Users\Dell\AppData\Local\Temp\ipykernel_10872\2498429054.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr1-arr2))


Array Slicing

In [79]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [80]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [88]:
arr[1][2]

7

Modify elements in array

In [91]:
arr[1][2]=100

print(arr)

[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [94]:
arr[1:,1:]=25

In [96]:
arr

array([[ 1,  2,  3,  4],
       [ 5, 25, 25, 25],
       [ 9, 25, 25, 25]])

Statistical operations

In [98]:
data = np.array([1, 2, 3, 4, 5])

In [101]:
np.mean(data)

3.0

In [109]:
print(np.std(data))

np.var(data)

1.4142135623730951


2.0

In [107]:
np.median(data)

3.0

In [105]:
np.mode(data)

AttributeError: module 'numpy' has no attribute 'mode'

Logical Operations

In [116]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[(data>=5) & (data<=8)])
print(data[(data>=5) | (data<=8)])
print(data[(data>=5) ^ (data<=8)])

[5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  9 10]


In [117]:
print(data[(data>=5) ~ (data<=8)])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (183965113.py, line 1)