In [2]:
import numpy as np
import math
from random import randint

# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
x=np.random.randint(1,20,size=(5,5))
print(f"Array: \n",x)

x[:,2]=1

print(f"Modified Array: \n",x)

Array: 
 [[12  9 18 19  6]
 [ 1  2 11 14 13]
 [ 9  9 16 17 16]
 [13 12  6  2 15]
 [ 8  3 19  1  6]]
Modified Array: 
 [[12  9  1 19  6]
 [ 1  2  1 14 13]
 [ 9  9  1 17 16]
 [13 12  1  2 15]
 [ 8  3  1  1  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [4]:
y=np.arange(1,17,1).reshape(4,4)
print(f"Array: \n",y)
np.fill_diagonal(y,0)
print(f"Diagonal 0 Array: \n",y)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal 0 Array: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [5]:
x=np.arange(1,37).reshape(6,6)
print(f"Array: \n",x)

y=x[2:5,1:4]
print(f"Sub-Array: \n",y)

Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-Array: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [6]:
a=np.random.randint(1,21,size=(5,5))
print(a)
print("\n")
p=a[0,:]
b=a[-1,:]
k=a[1:-1,0]
s=a[1:-1,-1]

o=np.concatenate((p,b,k,s))
print(o)

[[11  3 12  7 10]
 [19  1 20 20  5]
 [ 1  5 20  2 14]
 [ 3  2  4  7 18]
 [12 14  1 16  6]]


[11  3 12  7 10 12 14  1 16  6 19  1  3  5 14 18]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [7]:
arr1=np.random.randint(1,10,size=(3,4))
arr2=np.random.randint(1,10,size=(3,4))

print(f"Array1:\n",arr1)
print(f"Array2:\n",arr2)
print(f"Addition:\n",arr1+arr2)
print(f"Subtraction:\n",arr1-arr2)
print(f"Multiplication:\n",arr1*arr2)
print(f"Divison:\n",arr1/arr2)

Array1:
 [[9 1 5 6]
 [8 2 1 8]
 [9 9 9 4]]
Array2:
 [[5 1 3 1]
 [3 2 8 3]
 [5 3 1 5]]
Addition:
 [[14  2  8  7]
 [11  4  9 11]
 [14 12 10  9]]
Subtraction:
 [[ 4  0  2  5]
 [ 5  0 -7  5]
 [ 4  6  8 -1]]
Multiplication:
 [[45  1 15  6]
 [24  4  8 24]
 [45 27  9 20]]
Divison:
 [[1.8        1.         1.66666667 6.        ]
 [2.66666667 1.         0.125      2.66666667]
 [1.8        3.         9.         0.8       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [8]:
new=np.arange(1,17).reshape(4,4)
print(new)

row_wise=np.sum(new,axis=1).reshape(4,1)
print(f"Row wise sum:\n",row_wise)
column_size=np.sum(new,axis=0)
print(f"Column wise sum:",column_size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum:
 [[10]
 [26]
 [42]
 [58]]
Column wise sum: [28 32 36 40]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [9]:
stats=np.random.randint(1,50,size=(5,5))
print(stats)
print(f"Mean",np.mean(stats))
print(f"Median",np.median(stats))
print(f"Standard deviation",np.std(stats))
print(f"Variance",np.var(stats))

[[30  6 37 23 44]
 [13 25  6 45 14]
 [30 14 33  1 11]
 [ 5 28  8 42 18]
 [12  5 23 33 23]]
Mean 21.16
Median 23.0
Standard deviation 12.978998420525368
Variance 168.4544


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [14]:
first=np.arange(1,10).reshape(3,3)
print(f"Array: \n",first)
print(first.reshape(1,9))
print(first.reshape(9,1))

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [19]:
first=np.random.randint(1,20,size=(5,5))
print(f"Array: \n",first)
second=first.reshape(1,25)
print(f"Flatten array:\n",second)

'''
second=first.flatten()   this too works
'''

last=second.reshape(5,5)
print(f"Reshaped array:\n",last)

Array: 
 [[10  5 16  5 10]
 [19 11 15  7 12]
 [ 9 12 16 17  2]
 [18 19  8 18  8]
 [13 11  6 10  7]]
Flatten array:
 [[10  5 16  5 10 19 11 15  7 12  9 12 16 17  2 18 19  8 18  8 13 11  6 10
   7]]
Reshaped array:
 [[10  5 16  5 10]
 [19 11 15  7 12]
 [ 9 12 16 17  2]
 [18 19  8 18  8]
 [13 11  6 10  7]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [26]:
start=np.random.randint(1,20,size=(5,5))
print(start)
print(start[0,0])
print(start[0,-1])
print(start[-1,0])
print(start[-1,-1])

'''
this is a new type gives automatic list typo
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]  ##fancy indexing
'''

corners = start[[0, 0, -1, -1], [0, -1, 0, -1]]  
print(corners)

[[ 6 12 17  3  5]
 [10  1  5 10  2]
 [ 8 14  1  7  7]
 [12 14  6  4 15]
 [ 8  2 11 12  2]]
6
5
8
2
[6 5 8 2]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [38]:
old=np.random.randint(1,20,size=(4,4))
print(f"Array :\n",old)

new=old>10
print(new)

new_list=old[new]
print(new_list)

Array :
 [[ 6  2  1  1]
 [ 8 11 17  7]
 [ 4  9  1  6]
 [12 17 10 17]]
[[False False False False]
 [False  True  True False]
 [False False False False]
 [ True  True False  True]]
[11 17 12 17 17]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
