In [2]:
import numpy as np
import math
from random import randint

# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
x=np.random.randint(1,20,size=(5,5))
print(f"Array: \n",x)

x[:,2]=1

print(f"Modified Array: \n",x)

Array: 
 [[ 2 17 17  1 10]
 [ 6  9  4  4 15]
 [ 2 10  4 12  2]
 [19  4  2 16 18]
 [11 11 16 11 18]]
Modified Array: 
 [[ 2 17  1  1 10]
 [ 6  9  1  4 15]
 [ 2 10  1 12  2]
 [19  4  1 16 18]
 [11 11  1 11 18]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.


In [4]:
y=np.arange(1,17,1).reshape(4,4)
print(f"Array: \n",y)
np.fill_diagonal(y,0)
print(f"Diagonal 0 Array: \n",y)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal 0 Array: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]



### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [5]:
x=np.arange(1,37).reshape(6,6)
print(f"Array: \n",x)

y=x[2:5,1:4]
print(f"Sub-Array: \n",y)

Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-Array: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.


In [6]:
a=np.random.randint(1,21,size=(5,5))
print(a)
print("\n")
p=a[0,:]
b=a[-1,:]
k=a[1:-1,0]
s=a[1:-1,-1]

o=np.concatenate((p,b,k,s))
print(o)

[[17 13  3 12  5]
 [20 14  2 11 20]
 [19 14 10  6 15]
 [ 8  3 16 16 15]
 [ 5 17  3 10 11]]


[17 13  3 12  5  5 17  3 10 11 20 19  8 20 15 15]



### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.


In [7]:
arr1=np.random.randint(1,10,size=(3,4))
arr2=np.random.randint(1,10,size=(3,4))

print(f"Array1:\n",arr1)
print(f"Array2:\n",arr2)
print(f"Addition:\n",arr1+arr2)
print(f"Subtraction:\n",arr1-arr2)
print(f"Multiplication:\n",arr1*arr2)
print(f"Divison:\n",arr1/arr2)

Array1:
 [[1 5 4 1]
 [9 8 3 7]
 [7 7 7 7]]
Array2:
 [[8 8 7 3]
 [6 3 2 2]
 [2 9 2 3]]
Addition:
 [[ 9 13 11  4]
 [15 11  5  9]
 [ 9 16  9 10]]
Subtraction:
 [[-7 -3 -3 -2]
 [ 3  5  1  5]
 [ 5 -2  5  4]]
Multiplication:
 [[ 8 40 28  3]
 [54 24  6 14]
 [14 63 14 21]]
Divison:
 [[0.125      0.625      0.57142857 0.33333333]
 [1.5        2.66666667 1.5        3.5       ]
 [3.5        0.77777778 3.5        2.33333333]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [8]:
new=np.arange(1,17).reshape(4,4)
print(new)

row_wise=np.sum(new,axis=1).reshape(4,1)
print(f"Row wise sum:\n",row_wise)
column_size=np.sum(new,axis=0)
print(f"Column wise sum:",column_size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum:
 [[10]
 [26]
 [42]
 [58]]
Column wise sum: [28 32 36 40]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.


In [9]:
stats=np.random.randint(1,50,size=(5,5))
print(stats)
print(f"Mean",np.mean(stats))
print(f"Median",np.median(stats))
print(f"Standard deviation",np.std(stats))
print(f"Variance",np.var(stats))

[[42 15  1  2  8]
 [ 4 36 19 31 37]
 [47 38 26 45 46]
 [30 22 31 41 26]
 [31 40 15 22 37]]
Mean 27.68
Median 31.0
Standard deviation 13.736724500404017
Variance 188.6976


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [20]:
data=np.arange(1,10).reshape(3,3)
print(f"Array:\n",data)
mean=np.mean(data)
print(f"Mean:",mean)
std=np.std(data)
print(f"Standard Deviation:",std)
normalized_data=(data-mean)/std
print(f"Normalized array:\n",normalized_data)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean: 5.0
Standard Deviation: 2.581988897471611
Normalized array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [26]:
first=np.random.randint(1,10,size=(3,3))
print(f"Initial array:\n",first)
addon=np.random.randint(1,10,size=(3,))
print(f"1D array:\n",addon)

final=first+addon

print(f"Broadcasted array:\n",final)


Initial array:
 [[6 4 9]
 [1 2 7]
 [8 4 6]]
1D array:
 [3 8 2]
Broadcasted array:
 [[ 9 12 11]
 [ 4 10  9]
 [11 12  8]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.


In [27]:
first=np.random.randint(1,20,size=(4,4))
print(f"Initial array:\n",first)
subtracted=np.random.randint(1,10,size=(4,))
print(f"1D array:\n",subtracted)

final=first-subtracted

print(f"Broadcasted array:\n",final)

Initial array:
 [[19 18  1  1]
 [ 3 18 16  2]
 [19  5  9 11]
 [18 18  3 18]]
1D array:
 [6 8 6 5]
Broadcasted array:
 [[13 10 -5 -4]
 [-3 10 10 -3]
 [13 -3  3  6]
 [12 10 -3 13]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [51]:
array=np.random.randint(1,10,size=(3,3))
print(f"Array:\n",array)

determinant=np.linalg.det(array)
print(f"Determinant:\n",determinant)

inverse=np.linalg.inv(array)
print(f"Inverse:\n",inverse)

eigen_values=np.linalg.eigvals(array)
print(f"Eigen values:\n",eigen_values)

Array:
 [[1 4 5]
 [9 9 9]
 [6 7 4]]
Determinant:
 90.0
Inverse:
 [[-0.3         0.21111111 -0.1       ]
 [ 0.2        -0.28888889  0.4       ]
 [ 0.1         0.18888889 -0.3       ]]
Eigen values:
 [18.56921482 -2.89509855 -1.67411627]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [46]:
a=np.random.randint(1,10,size=(2,3))
print(f"First array:\n",a)
b=np.random.randint(1,10,size=(3,2))
print(f"Second array:\n",b)
mul=np.matmul(a,b)
'''
mul=np.dot(a,b)  #also works
'''
print(mul)
print(f"Final array:\n",mul)

First array:
 [[1 8 3]
 [8 3 1]]
Second array:
 [[5 4]
 [4 7]
 [6 5]]
[[55 75]
 [58 58]]
Final array:
 [[55 75]
 [58 58]]



### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [11]:
first=np.arange(1,10).reshape(3,3)
print(f"Array: \n",first)
print(first.reshape(1,9))
print(first.reshape(9,1))

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).


In [12]:
first=np.random.randint(1,20,size=(5,5))
print(f"Array: \n",first)
second=first.reshape(1,25)
print(f"Flatten array:\n",second)

'''
second=first.flatten()  #this too works
'''

last=second.reshape(5,5)
print(f"Reshaped array:\n",last)

Array: 
 [[ 4  3  8  9 17]
 [16 12 16 18 14]
 [ 8  2 14  2 11]
 [ 6  1  8  1 18]
 [16 19 19  2 18]]
Flatten array:
 [[ 4  3  8  9 17 16 12 16 18 14  8  2 14  2 11  6  1  8  1 18 16 19 19  2
  18]]
Reshaped array:
 [[ 4  3  8  9 17]
 [16 12 16 18 14]
 [ 8  2 14  2 11]
 [ 6  1  8  1 18]
 [16 19 19  2 18]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [13]:
start=np.random.randint(1,20,size=(5,5))
print(start)
print(start[0,0])
print(start[0,-1])
print(start[-1,0])
print(start[-1,-1])

'''
this is a new type gives automatic list typo
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]  ##fancy indexing
'''

corners = start[[0, 0, -1, -1], [0, -1, 0, -1]]  
print(corners)

[[ 5 15  8 14 11]
 [ 5 10  4  2 18]
 [ 6 11 17  6  9]
 [ 2 13 17 17  3]
 [10 19 15  8 18]]
5
11
10
18
[ 5 11 10 18]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [14]:
old=np.random.randint(1,20,size=(4,4))
print(f"Array :\n",old)

new=old>10
print(new)

new_list=old[new]
print(new_list)

Array :
 [[ 6 10  8 13]
 [13 14  1  4]
 [ 6 16 19  3]
 [17  2 12  1]]
[[False False False  True]
 [ True  True False False]
 [False  True  True False]
 [ True False  True False]]
[13 13 14 16 19 17 12]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [78]:
dt=np.dtype([("name",np.str_,10),("age",np.int32),("weight",np.float64)])
'''
dt = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
'''
main=np.array([("Raghu",19,69),("Akash",20,68),("Thala",43,75),("King",36,65)],dtype=dt)
print(main)

new=np.sort(main,order=["age"])
print(new)

[('Raghu', 19, 69.) ('Akash', 20, 68.) ('Thala', 43, 75.)
 ('King', 36, 65.)]
[('Raghu', 19, 69.) ('Akash', 20, 68.) ('King', 36, 65.)
 ('Thala', 43, 75.)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
